"""add_user_default_connection_id

Revision ID: 84029ea1446b
Revises: 8956fdf03bbb
Create Date: 2026-04-18 14:10:45.760608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84029ea1446b'
down_revision: Union[str, None] = '8956fdf03bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_connection_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_default_connection_id_connections'), 'connections', ['default_connection_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_default_connection_id_connections'), type_='foreignkey')
        batch_op.drop_column('default_connection_id')

    # ### end Alembic commands ###
