/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as UserRouteImport } from './routes/_user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserChatRouteImport } from './routes/_user/chat'
import { Route as AdminConfigRouteImport } from './routes/_admin/config'
import { Route as UserChatIndexRouteImport } from './routes/_user/chat.index'
import { Route as UserChatConversationIdRouteImport } from './routes/_user/chat.$conversationId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserChatRoute = UserChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => UserRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/_admin/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const UserChatIndexRoute = UserChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserChatRoute,
} as any)
const UserChatConversationIdRoute = UserChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => UserChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/config': typeof AdminConfigRoute
  '/chat': typeof UserChatRouteWithChildren
  '/chat/$conversationId': typeof UserChatConversationIdRoute
  '/chat/': typeof UserChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/config': typeof AdminConfigRoute
  '/chat/$conversationId': typeof UserChatConversationIdRoute
  '/chat': typeof UserChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_user': typeof UserRouteWithChildren
  '/admin': typeof AdminRoute
  '/_admin/config': typeof AdminConfigRoute
  '/_user/chat': typeof UserChatRouteWithChildren
  '/_user/chat/$conversationId': typeof UserChatConversationIdRoute
  '/_user/chat/': typeof UserChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/config'
    | '/chat'
    | '/chat/$conversationId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/config' | '/chat/$conversationId' | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_user'
    | '/admin'
    | '/_admin/config'
    | '/_user/chat'
    | '/_user/chat/$conversationId'
    | '/_user/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdminConfigRoute: typeof AdminConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/chat': {
      id: '/_user/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof UserChatRouteImport
      parentRoute: typeof UserRoute
    }
    '/_admin/config': {
      id: '/_admin/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/chat/': {
      id: '/_user/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof UserChatIndexRouteImport
      parentRoute: typeof UserChatRoute
    }
    '/_user/chat/$conversationId': {
      id: '/_user/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof UserChatConversationIdRouteImport
      parentRoute: typeof UserChatRoute
    }
  }
}

interface UserChatRouteChildren {
  UserChatConversationIdRoute: typeof UserChatConversationIdRoute
  UserChatIndexRoute: typeof UserChatIndexRoute
}

const UserChatRouteChildren: UserChatRouteChildren = {
  UserChatConversationIdRoute: UserChatConversationIdRoute,
  UserChatIndexRoute: UserChatIndexRoute,
}

const UserChatRouteWithChildren = UserChatRoute._addFileChildren(
  UserChatRouteChildren,
)

interface UserRouteChildren {
  UserChatRoute: typeof UserChatRouteWithChildren
}

const UserRouteChildren: UserRouteChildren = {
  UserChatRoute: UserChatRouteWithChildren,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRouteWithChildren,
  AdminRoute: AdminRoute,
  AdminConfigRoute: AdminConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
